language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
branches:
  only:
    - master

install:
  - composer install --dev

script:
  - vendor/bin/ecs --level psr12 check src
  - vendor/bin/phpunit
  - php check-coverage.php coverage.xml 100
