language: php
php:
  - '7.1'
branches:
  only:
    - master

install:
  - composer install --dev

script:
  - vendor/bin/ecs --level psr12 check src
  - vendor/bin/phpunit --coverage-text --coverage-clover coverage.xml
  - php check-coverage.php coverage.xml 100

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
